#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-mariadb-soname18
Version  : 10.1.37
Release  : 5
URL      : http://ftp.hosteurope.de/mirror/archive.mariadb.org/mariadb-10.1.37/source/mariadb-10.1.37.tar.gz
Source0  : http://ftp.hosteurope.de/mirror/archive.mariadb.org/mariadb-10.1.37/source/mariadb-10.1.37.tar.gz
Summary  : zlib compression library
Group    : Development/Tools
License  : AGPL-3.0 BSD-3-Clause BSD-3-Clause-Clear GPL-2.0 GPL-3.0 LGPL-2.1 OpenSSL
Requires: compat-mariadb-soname18-lib = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-php
BuildRequires : curl-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : jemalloc-dev
BuildRequires : libaio-dev
BuildRequires : libxml2-dev
BuildRequires : ncurses-dev
BuildRequires : openjdk11
BuildRequires : openjdk11-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(libzstd)
BuildRequires : zlib-dev

%description
MariaDB is designed as a drop-in replacement of MySQL(R) with more
features, new storage engines, fewer bugs, and better performance.

%package lib
Summary: lib components for the compat-mariadb-soname18 package.
Group: Libraries

%description lib
lib components for the compat-mariadb-soname18 package.


%prep
%setup -q -n mariadb-10.1.37

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564080079
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_CONFIG=mysql_release \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_C_FLAGS="-fPIC $CFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer -fno-delete-null-pointer-checks" \
-DCMAKE_CXX_FLAGS="-fPIC $CXXFLAGS -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors -fno-rtti -fno-delete-null-pointer-checks" \
-DCMAKE_INSTALL_PREFIX=/usr \
-DENABLED_LOCAL_INFILE=ON \
-DINSTALL_DOCDIR="share/doc/mariadb" \
-DINSTALL_DOCREADMEDIR="share/doc/mariadb" \
-DINSTALL_INCLUDEDIR=include/mysql \
-DINSTALL_INFODIR=share/info \
-DINSTALL_LAYOUT=RPM \
-DINSTALL_LIBDIR="lib64" \
-DINSTALL_MANDIR=share/man \
-DINSTALL_MYSQLSHAREDIR=share/mariadb \
-DINSTALL_MYSQLTESTDIR=share/mysql-test \
-DINSTALL_PLUGINDIR="lib64/mysql/plugin" \
-DINSTALL_SBINDIR=sbin \
-DINSTALL_SCRIPTDIR=bin \
-DINSTALL_SHAREDIR=share/aclocal/mysql \
-DINSTALL_SUPPORTFILESDIR=share/mariadb \
-DINSTALL_SYSCONF2DIR="/usr/share/defaults/mariadb/my.cnf.d" \
-DINSTALL_SYSCONFDIR="/usr/share/defaults/mariadb" \
-DMYSQL_DATADIR="/var/lib/mysql" \
-DMYSQL_UNIX_ADDR=/run/mariadb/mariadb.sock \
-DTMPDIR=/var/tmp \
-DWITH_EMBEDDED_SERVER=OFF \
-DWITH_JEMALLOC=yes \
-DWITH_MYSQLD_LDFLAGS="-pie -Wl,-z,now" \
-DWITH_SSL=system \
-DWITH_ZLIB=system \
-DWITHOUT_MROONGA=True \
-DWITHOUT_TOKUDB=True \
-DWITH_SSL=bundled
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1564080079
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18
cp COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/COPYING
cp COPYING.thirdparty %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/COPYING.thirdparty
cp extra/readline/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/extra_readline_COPYING
cp extra/yassl/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/extra_yassl_COPYING
cp extra/yassl/taocrypt/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/extra_yassl_taocrypt_COPYING
cp pcre/LICENCE %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/pcre_LICENCE
cp pcre/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/pcre_cmake_COPYING-CMAKE-SCRIPTS
cp plugin/handler_socket/handlersocket/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/plugin_handler_socket_handlersocket_COPYRIGHT.txt
cp plugin/handler_socket/libhsclient/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/plugin_handler_socket_libhsclient_COPYRIGHT.txt
cp plugin/handler_socket/perl-Net-HandlerSocket/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/plugin_handler_socket_perl-Net-HandlerSocket_COPYRIGHT.txt
cp plugin/server_audit/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/plugin_server_audit_COPYING
cp storage/innobase/COPYING.Google %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_innobase_COPYING.Google
cp storage/innobase/COPYING.Percona %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_innobase_COPYING.Percona
cp storage/mroonga/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_mroonga_COPYING
cp storage/mroonga/vendor/groonga/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_mroonga_vendor_groonga_COPYING
cp storage/mroonga/vendor/groonga/vendor/plugins/groonga-normalizer-mysql/packages/debian/copyright %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_mroonga_vendor_groonga_vendor_plugins_groonga-normalizer-mysql_packages_debian_copyright
cp storage/tokudb/PerconaFT/COPYING.AGPLv3 %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_tokudb_PerconaFT_COPYING.AGPLv3
cp storage/tokudb/PerconaFT/COPYING.GPLv2 %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_tokudb_PerconaFT_COPYING.GPLv2
cp storage/tokudb/PerconaFT/third_party/snappy-1.1.2/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_tokudb_PerconaFT_third_party_snappy-1.1.2_COPYING
cp storage/tokudb/PerconaFT/third_party/xz-4.999.9beta/COPYING %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_tokudb_PerconaFT_third_party_xz-4.999.9beta_COPYING
cp storage/tokudb/PerconaFT/third_party/xz-4.999.9beta/COPYING.GPLv2 %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_tokudb_PerconaFT_third_party_xz-4.999.9beta_COPYING.GPLv2
cp storage/tokudb/PerconaFT/third_party/xz-4.999.9beta/COPYING.GPLv3 %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_tokudb_PerconaFT_third_party_xz-4.999.9beta_COPYING.GPLv3
cp storage/tokudb/PerconaFT/third_party/xz-4.999.9beta/COPYING.LGPLv2.1 %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_tokudb_PerconaFT_third_party_xz-4.999.9beta_COPYING.LGPLv2.1
cp storage/xtradb/COPYING.Google %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_xtradb_COPYING.Google
cp storage/xtradb/COPYING.Percona %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/storage_xtradb_COPYING.Percona
cp vio/docs/COPYING.openssl %{buildroot}/usr/share/package-licenses/compat-mariadb-soname18/vio_docs_COPYING.openssl
pushd clr-build
%make_install
popd
## install_append content
rm -rf %{buildroot}/usr/bin
rm -rf %{buildroot}/usr/share
rm -rf %{buildroot}/usr/lib
rm -rf %{buildroot}/usr/include
rm -rf %{buildroot}/usr/lib64/mysql
rm -rf %{buildroot}/usr/lib64/*.so
## install_append end

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmysqlclient.so.18
/usr/lib64/libmysqlclient.so.18.0.0
/usr/lib64/libmysqlclient_r.so.18
/usr/lib64/libmysqlclient_r.so.18.0.0
